const { test, expect } = require('@playwright/test');
const OPE_IDS=['puebla-aux-admin-2026','carranque-aux-admin-2026','diputacion-toledo-admin-2026','uc3m-aux-admin-2026'];
const TITLES={proceso:'Proceso y enlaces',temario:'Temario',normas:'Normas',tests:'Test por temas',supuestos:'Supuestos prácticos',simulacros:/Simulacros/,progreso:'Progreso'};
const headings=['Resumen orientado al aprobado','Rigor normativo','Desarrollo completo del epígrafe oficial','Síntesis de repaso rápido','Opo-Test: puntos calientes','Tres preguntas de retención activa','Estrategia de examen'];
async function openNav(page){const b=page.locator('#openSidebar');if(await b.isVisible()){await b.click();await expect(page.locator('#sidebar')).toHaveClass(/open/);}}
async function closeNav(page){const b=page.locator('#closeSidebar');if(await b.isVisible()&&await page.locator('#sidebar').evaluate(n=>n.classList.contains('open'))){await b.click();await expect(page.locator('#sidebar')).not.toHaveClass(/open/);}}
async function navigate(page,view){await openNav(page);await page.locator(`.menu button[data-view="${view}"]`).click();await closeNav(page);await expect(page.locator('#viewTitle')).toHaveText(TITLES[view]);await expect(page.locator('#content')).toBeVisible();}
async function waitBoot(page){await expect.poll(()=>page.evaluate(()=>window.OPOWEB_BOOT_V83?.status||'missing'),{timeout:60000}).toBe('ready');}
async function load(page){const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/index.html',{waitUntil:'domcontentloaded'});await waitBoot(page);await expect(page.locator('#content')).toBeVisible();await expect(page.locator('#oposicionSelect option')).toHaveCount(4);return errors;}

test('carga las cuatro OPE, todos los módulos y las siete vistas',async({page},testInfo)=>{
 const errors=await load(page);expect(await page.locator('#oposicionSelect option').evaluateAll(os=>os.map(o=>o.value))).toEqual(OPE_IDS);await expect(page.locator('#oposicionCard')).toContainText('Versión OpoWeb v0.87.0');
 const boot=await page.evaluate(()=>{const m=window.OPOWEB_ASSET_MANIFEST_V83,b=window.OPOWEB_BOOT_V83,loaded=[...document.querySelectorAll('script[data-opoweb-managed="v83"]')].map(s=>new URL(s.src).pathname),expected=m.scripts.map(s=>new URL(s,location.href).pathname);return{status:b.status,failed:b.failed,loaded:b.loaded.length,declared:m.scripts.length,version:m.applicationVersion,duplicates:window.OPOWEB_LOADER_AUDIT_V83.duplicateScripts,order:JSON.stringify(loaded)===JSON.stringify(expected),carranque:window.OPOWEB_THEORY_AUDIT_V85?.carranque?.autonomousThemes,puebla:window.OPOWEB_PUEBLA_THEORY_V86?.autonomousThemes,diputacion:window.OPOWEB_UI_V87?.diputacionAutonomousThemes,dipQuestions:window.OPOWEB_UI_V87?.diputacionQuestions,globalQuestions:window.OPOWEB_UI_V87?.globalQuestions,snapshot:window.OPOWEB_DIPUTACION_SNAPSHOT_V87?.totalQuestions,addedBlock3:window.OPOWEB_DIPUTACION_TEST_V87_BLOQUE3?.totalAdded,addedBlock4:window.OPOWEB_DIPUTACION_TEST_V87_BLOQUE4?.totalAdded,addedBlock5:window.OPOWEB_DIPUTACION_TEST_V87_BLOQUE5?.totalAdded,oapgt:window.OPOWEB_UI_V87?.oapgtStatutesVerified};});
 expect(boot).toMatchObject({status:'ready',failed:null,version:'v0.87.0',duplicates:0,order:true,carranque:20,puebla:19,diputacion:16,dipQuestions:1450,globalQuestions:3310,snapshot:1433,addedBlock3:3,addedBlock4:2,addedBlock5:1,oapgt:false});expect(boot.loaded).toBe(boot.declared);
 await page.locator('#oposicionSelect').selectOption('uc3m-aux-admin-2026');for(const view of Object.keys(TITLES))await navigate(page,view);await expect(page.locator('#loaderAuditV83')).toContainText('LISTO');expect(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1),`Desbordamiento horizontal en ${testInfo.project.name}`).toBeFalsy();expect(errors).toEqual([]);
});

test('La Puebla conserva sus diecinueve temas autosuficientes',async({page})=>{const errors=await load(page);await page.locator('#oposicionSelect').selectOption('puebla-aux-admin-2026');await navigate(page,'temario');await expect(page.locator('#pueblaTheoryStatusV86')).toContainText('La Puebla 19/19');await expect(page.locator('.theme-item')).toHaveCount(19);const r=await page.evaluate(()=>{const o=window.OPOSICIONES_DATA.oposiciones.find(x=>x.id==='puebla-aux-admin-2026');return{status:o.theoryProgramme.v86.status,completed:o.theoryProgramme.v86.completedThemes.length,pending:o.theoryProgramme.v86.pendingThemes.length,questions:Object.values(o.themeTests).reduce((s,b)=>s+b.length,0)};});expect(r).toEqual({status:'APTO',completed:19,pending:0,questions:570});expect(errors).toEqual([]);});

test('Carranque conserva sus veinte temas autosuficientes',async({page})=>{const errors=await load(page);await page.locator('#oposicionSelect').selectOption('carranque-aux-admin-2026');await navigate(page,'temario');await expect(page.locator('#theoryStatusV85')).toContainText('Carranque 20/20');await expect(page.locator('.theme-item')).toHaveCount(20);const r=await page.evaluate(()=>{const o=window.OPOSICIONES_DATA.oposiciones.find(x=>x.id==='carranque-aux-admin-2026');return{completed:o.theoryProgramme.v85.completedThemes.length,pending:o.theoryProgramme.v85.pendingThemes.length};});expect(r).toEqual({completed:20,pending:0});expect(errors).toEqual([]);});

test('Diputación publica dieciséis temas autosuficientes sin ocultar los pendientes',async({page})=>{
 const errors=await load(page);await page.locator('#oposicionSelect').selectOption('diputacion-toledo-admin-2026');await navigate(page,'temario');await expect(page.locator('#diputacionTheoryStatusV87')).toContainText('Diputación 16/40');await expect(page.locator('#diputacionTheoryStatusV87')).toContainText('todavía no debe utilizarse como fuente única');await expect(page.locator('#diputacionTheoryStatusV87')).toContainText('contenido estatutario bloqueado');await expect(page.locator('.theme-item')).toHaveCount(40);
 await page.locator('.theme-item').nth(38).click();await expect(page.locator('#diputacionThemeSourcesV87')).toContainText('Tema autosuficiente');for(const h of headings)await expect(page.locator('#content')).toContainText(h);await expect(page.locator('#content')).toContainText('memoria RAM');
 const r=await page.evaluate(()=>{const o=window.OPOSICIONES_DATA.oposiciones.find(x=>x.id==='diputacion-toledo-admin-2026'),p=o.theoryProgramme.v87,completed=Array.from({length:16},(_,i)=>i+25);const metrics=completed.map(n=>{const t=o.themes.find(x=>Number(x.number)===n),text=[...(t.sections||[]).flatMap(s=>[s.heading,...(s.paragraphs||[])]),t.tree||'',...(t.reviewTable||[]).flat()].join(' ');return{autonomous:t.theoryStatus?.autonomous===true,words:text.trim().split(/\s+/).filter(Boolean).length,sources:(t.officialSources||[]).length,questions:(o.themeTests[t.id]||[]).length};});return{status:p.status,completed:p.completedThemes,pending:p.pendingThemes.length,questions:Object.values(o.themeTests).reduce((s,b)=>s+b.length,0),snapshot:window.OPOWEB_DIPUTACION_SNAPSHOT_V87.totalQuestions,added:window.OPOWEB_DIPUTACION_TEST_V87.totalAdded,addedBlock3:window.OPOWEB_DIPUTACION_TEST_V87_BLOQUE3.totalAdded,addedBlock4:window.OPOWEB_DIPUTACION_TEST_V87_BLOQUE4.totalAdded,addedBlock5:window.OPOWEB_DIPUTACION_TEST_V87_BLOQUE5.totalAdded,oapgt:window.OPOWEB_OAPGT_FUENTES_V87.statutes.allowedForTheory,metrics};});
 expect(r.status).toBe('EN_PROGRESO');expect(r.completed).toEqual(Array.from({length:16},(_,i)=>i+25));expect(r.pending).toBe(24);expect(r.snapshot).toBe(1433);expect(r.added).toBe(11);expect(r.addedBlock3).toBe(3);expect(r.addedBlock4).toBe(2);expect(r.addedBlock5).toBe(1);expect(r.questions).toBe(1450);expect(r.oapgt).toBe(false);expect(r.metrics.every(x=>x.autonomous&&x.words>=900&&x.sources>=2&&x.questions>=30)).toBe(true);expect(errors).toEqual([]);
});

test('guarda y recupera el progreso tras recargar',async({page})=>{const errors=await load(page);await page.locator('#oposicionSelect').selectOption('uc3m-aux-admin-2026');await navigate(page,'tests');await page.locator('.question input[type="radio"]').first().check();await page.locator('#correctSet').click();await expect(page.locator('.result-box').first()).toBeVisible();const saved=await page.evaluate(()=>localStorage.getItem('opowebProgress'));await page.reload({waitUntil:'domcontentloaded'});await waitBoot(page);expect(await page.evaluate(()=>localStorage.getItem('opowebProgress'))).toBe(saved);expect(errors).toEqual([]);});

test('la PWA v95 funciona sin conexión y conserva datos',async({page,context},testInfo)=>{test.skip(testInfo.project.name!=='desktop-chromium','La prueba PWA completa se ejecuta una vez.');const errors=await load(page);await page.evaluate(()=>navigator.serviceWorker.ready);if(!await page.evaluate(()=>Boolean(navigator.serviceWorker.controller))){await page.reload({waitUntil:'domcontentloaded'});await waitBoot(page);}await expect.poll(()=>page.evaluate(()=>Boolean(navigator.serviceWorker.controller))).toBeTruthy();await expect.poll(()=>page.evaluate(async()=>(await caches.keys()).includes('opoweb-v95')),{timeout:30000}).toBeTruthy();const paths=await page.evaluate(async()=>{const c=await caches.open('opoweb-v95');return(await c.keys()).map(r=>new URL(r.url).pathname);});for(const p of ['/index.html','/assets/js/asset-manifest-v83.js','/assets/js/loader-v83.js','/data/oapgt-fuentes-v87.js','/assets/js/diputacion-snapshot-v87.js','/assets/js/diputacion-teoria-v87-bloque1.js','/assets/js/diputacion-teoria-v87-bloque2.js','/assets/js/diputacion-test-v87-bloque2.js','/assets/js/diputacion-teoria-v87-bloque3.js','/assets/js/diputacion-test-v87-bloque3.js','/assets/js/diputacion-teoria-v87-bloque4.js','/assets/js/diputacion-test-v87-bloque4.js','/assets/js/diputacion-teoria-v87-bloque5.js','/assets/js/diputacion-test-v87-bloque5.js','/assets/js/ui-v87.js','/manifest.webmanifest'])expect(paths).toContain(p);const progress={'diputacion-toledo-admin-2026:test:offline-check':{answers:{prueba:'A'},corrected:false,score:null}};await page.evaluate(v=>localStorage.setItem('opowebProgress',JSON.stringify(v)),progress);await context.setOffline(true);await page.reload({waitUntil:'domcontentloaded'});await waitBoot(page);await expect(page.locator('#oposicionCard')).toContainText('Versión OpoWeb v0.87.0');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('opowebProgress')||'{}'))).toEqual(progress);expect(errors).toEqual([]);await context.setOffline(false);});
