const fs = require('fs');
const path = require('path');
const vm = require('vm');
const assert = require('assert');
const root=process.cwd(),read=file=>fs.readFileSync(path.join(root,file),'utf8'),exists=file=>fs.existsSync(path.join(root,file)),normalize=value=>value.replace(/^\.\//,'');
const context={};vm.createContext(context);vm.runInContext(read('assets/js/asset-manifest-v83.js'),context,{filename:'asset-manifest-v83.js'});const manifest=context.OPOWEB_ASSET_MANIFEST_V83;
assert.ok(manifest);assert.equal(manifest.applicationVersion,'v0.87.0');assert.equal(manifest.cacheName,'opoweb-v95');assert.ok(manifest.scripts.length>120);assert.equal(new Set(manifest.scripts).size,manifest.scripts.length);assert.equal(new Set(manifest.allAssets).size,manifest.allAssets.length);assert.deepStrictEqual(JSON.parse(JSON.stringify(manifest.allAssets)),[...manifest.staticAssets,...manifest.scripts]);
for(const asset of manifest.allAssets){const file=normalize(asset);if(file)assert.ok(exists(file),`Recurso declarado inexistente: ${asset}`);}
const position=asset=>manifest.scripts.indexOf(asset);assert.equal(manifest.scripts[0],'./data/oposiciones.js');assert.equal(manifest.scripts.at(-1),'./assets/js/ui-v87.js');assert.ok(position('./data/oapgt-fuentes-v87.js')>position('./data/ope-audit-v41.js'));assert.ok(position('./assets/js/storage-v82.js')<position('./assets/js/app.js'));assert.ok(position('./assets/js/diputacion-v65.js')<position('./assets/js/diputacion-snapshot-v87.js'));assert.ok(position('./assets/js/diputacion-snapshot-v87.js')<position('./assets/js/puebla-v68.js'));assert.ok(position('./assets/js/auditoria-calidad-v72.js')<position('./assets/js/ui-v42.js'));assert.ok(position('./assets/js/ui-v86.js')<position('./assets/js/diputacion-teoria-v87-bloque1.js'));
const ordered=['./assets/js/diputacion-teoria-v87-bloque1.js','./assets/js/diputacion-teoria-v87-bloque2.js','./assets/js/diputacion-test-v87-bloque2.js','./assets/js/diputacion-teoria-v87-bloque3.js','./assets/js/diputacion-test-v87-bloque3.js','./assets/js/diputacion-teoria-v87-bloque4.js','./assets/js/diputacion-teoria-v87-bloque5.js','./assets/js/ui-v87.js'];for(let i=1;i<ordered.length;i++)assert.ok(position(ordered[i-1])<position(ordered[i]),`${ordered[i-1]} debe preceder a ${ordered[i]}`);
const index=read('index.html'),scriptSources=[...index.matchAll(/<script\s+src="([^"]+)"/g)].map(match=>match[1]);assert.deepStrictEqual(scriptSources,['assets/js/asset-manifest-v83.js','assets/js/loader-v83.js']);assert.ok(!index.includes('assets/js/app.js'));
const loader=read('assets/js/loader-v83.js');assert.ok(/for \(const source of manifest\.scripts\) await loadScript\(source\)/.test(loader));assert.ok(/opoweb:ready/.test(loader));assert.ok(/opoweb:failed/.test(loader));assert.ok(/serviceWorker\.register\('\.\/sw\.js'\)/.test(loader));
const serviceWorker=read('sw.js');assert.ok(serviceWorker.includes("importScripts('./assets/js/asset-manifest-v83.js')"));assert.ok(serviceWorker.includes('const CACHE = MANIFEST.cacheName'));assert.ok(serviceWorker.includes('const ASSETS = MANIFEST.allAssets'));assert.ok(!/const ASSETS = \[/.test(serviceWorker));
console.log(`Cargador v0.87 OK · ${manifest.scripts.length} módulos · ${manifest.allAssets.length} recursos · Diputación 16/40`);
